### ISSUE TITLE
Unable to compile `spirv-std-macros` with old `Cargo.lock`.

### ISSUE THREAD

**Issue by dsvensson** [EmbarkStudios/rust-gpu#1053]
When trying to get [this project](https://github.com/hatoo/ash-raytracing-example) working with more recent versions of dependencies I get the following with spirv-std bumped to 0.7.0

```
error[E0599]: no method named `token` found for struct `LitStr` in the current scope
   --> C:\....\.cargo\registry\src\index.crates.io-6f17d22bba15001f\spirv-std-macros-0.7.0\src\lib.rs:790:65
    |
790 | ...                   new_t.push(TokenTree::Literal(l.token()));
    |                                                       ^^^^^ method not found in `LitStr`
```

I bumped the rust-toolchain.toml to the same as in this repo fwiw.

**Comment by eddyb** [comment]
Does this go away when you run `cargo update -p syn`? If so, the issue is that we only require an old version:
https://github.com/EmbarkStudios/rust-gpu/blob/a64857af0247dabdf08103b9c91ce0355c6530b8/crates/spirv-std/macros/Cargo.toml#L17
But some other dependencies are forcing newer versions:
https://github.com/EmbarkStudios/rust-gpu/blob/a64857af0247dabdf08103b9c91ce0355c6530b8/Cargo.lock#L2386-L2388

Thankfully, this shouldn't affect newer projects, as Cargo will always pick the newest version when creating the `Cargo.lock`, but it is a mistake on our part and we should be careful with dependencies like that.

This is probably not strong enough, but we should at least [run `cargo update -Z minimal-versions`](https://github.com/rust-lang/cargo/issues/4100) in CI, to force dependency versions in `Cargo.toml` files to be large enough to allow building & passing tests (cc @repi).

But I just tried that and it fails to compile `anyhow 1.0.0`, so that probably means the ecosystem isn't necessarily readily to do something that broad. Also, it would perhaps be nicer if we just forced version bumps in `Cargo.lock` to be reflected in `Cargo.toml`, instead, but I can't find a command that would make the two equal.

**Comment by eddyb** [comment]
@dsvensson I've opened a tentative fix:
* #1054

But note that the simplest fix for that project is still likely running `cargo update -p syn`.

**Comment by dsvensson** [comment]
Aha, doh, so deleting Cargo.lock and rebuilding, should have tried. :man_facepalming: Thanks.

**Comment by dsvensson** [comment]
Agree generally, but this is a small toy project almost no deps, and I'm just scouting around various vulkan related projects.
