### ISSUE TITLE
Suggestion: Don't name everything after spirv.

### ISSUE THREAD

**Issue by lachlansneff** [EmbarkStudios/rust-gpu#128]
# Proposal
I'm suggesting that the rust-gpu project doesn't name all the attributes and crates after "spirv". There are many gpu languages, and restricting this project to just spirv so early one might not be a good idea. And if it expands later to other languages, but the attributes and crates are still called spirv, it could pretty easily get confusing.

Instead, name things `shader` or `gpu`. e.g. `#[shader(...)]` and `use std_shader::...`.

**Comment by repi** [comment]
Agreed! Which is why we also overall called the project/repo "Rust GPU" and have https://shader.rs :) 
Do hope that the current `spirv-std` will evolve to a `std-shader` (or `std-gpu` or similar). 

There are some SPIRV-specific intrinsics and types also though on the lower layers, but now when we can do `#[cfg(target_arch = "spirv")]` that will be very helpful in our own crates as well as others crates to compile in SPIRV-specifics but building general crates that can be compile for multiple targets, including CPU.

**Comment by XAMPPRocky** [comment]
We discussed at the meeting, and the consensus was that we are in favour of changing the name, but want to wait until project is further along before renaming anything. So I'm going to close this for now.
