### ISSUE TITLE
Implement copysignf32

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/rust-gpu#148]
We have an implementation of it for OpenCL Kernel compute mode, but not for the "GL Compute" mode where it looks like there is no 1-to-1 mapping for it.

```
  error: TODO: Shader copysign not supported yet
    --> spirv-std\src\math_ext.rs:82:18
     |
  82 |         unsafe { core::intrinsics::copysignf32(self, sign) }
     |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

This is needed by glam (#134) as `f32::signum` uses it

**Comment by bjorn3** [comment]
`copysign` can be implemented using bit manipulation. I think the following will work:

```rust
f32::from_bits((this.to_bits() & (u32::max_value() >> 1)) | (sign.to_bits() & (1 << 31)))
```

**Comment by khyperia** [comment]
Hrmpf. Looks like `f32::from_bits`/`to_bits` calls a pointercast on `*u32 -> *f32`, not a bitcast on `u32 -> f32`, so looks like we don't actually support `f32::from_bits` right now - doesn't matter for this, though, as we'll be implementing it inside the compiler directly emitting a sequence of spir-v insts rather than a Rust implementation, but we can't take a mental shortcut and get that sequence of insts by compiling that rust.
