### ISSUE TITLE
wgpu-example-runner throws vulkan validation error

### ISSUE THREAD

**Issue by nipunG314** [EmbarkStudios/rust-gpu#163]
### Expected Behaviour
wgpu-example-runner should show no errors or warnings during or post execution.

### Example & Steps To Reproduce

Running wgpu-example-runner on my system shows the following warning as a part of the Vulkan Validation layer:

```bash
[1.265265 ERROR]()(no module): 
VALIDATION [UNASSIGNED-CoreValidation-Shader-InconsistentSpirv (7060244)] : Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x556ecb32ae90, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Invalid SPIR-V binary version 1.3 for target environment SPIR-V 1.0 (under Vulkan 1.0 semantics).
object info: (type: DEVICE, hndl: 93934343859856)
```

The binary runs properly and exits properly without crashing.

## System Info

 - Rust: 1.49.0-nightly (ffa2e7ae8 2020-10-24)
 - OS: Ubuntu 18.04.4 LTS
 - GPU: NVIDIA GeForce 940MX
 - SPIR-V: v2020.3

**Comment by termhn** [comment]
This is a known issue but I don't think there's been a tracking issue for it on GitHub yet. It's due to the fact that gfx-hal (and by extension wgpu) are hardcoded to use Vulkan version 1.0.0 which supports only SPIR-V version 1.0. This is probably something that we want to figure out in terms of whether rust-gpu should support Vulkan/SPIR-V 1.0 explicitly or not.

Currently, it's ignorable, it's an 'error' but the shader still runs properly.

**Comment by termhn** [comment]
Actually going to make a separate issue for the design decision and leave this one to just track this 'bug'

**Comment by khyperia** [comment]
Is this "fixed" by https://github.com/EmbarkStudios/rust-gpu/pull/165, or should we turn this into a tracking issue to get wgpu/gfx-hal to use vulkan 1.1?

**Comment by XAMPPRocky** [comment]
Well I think if anything we'd want to close this one and re-open #164  for tracking.

**Comment by khyperia** [comment]
Eh, the wgpu binary is now being built for 1.0, and this is kind of just waiting for wgpu/gfx-hal to use vulkan 1.1, so I'll close this instead of forever waiting for them.
