### ISSUE TITLE
Documenting Platform Support

### ISSUE THREAD

**Issue by XAMPPRocky** [EmbarkStudios/rust-gpu#177]
As discussed in the last meeting, we want to clarify what platforms, vendors, and versions we support, and what we're focusing on right on now. the outcome of this would be a page in the GPU dev guide that provides an overview the support and what that kind of support means for the platforms.

**Comment by Jasper-Bekkers** [comment]
I think we should just focus on Vulkan 1.1 at the moment (MoltenVK supports 1.1 and it fixes a whole bunch of issues that 1.0 has).

I think staying on SPIR-V 1.3 at the moment is fine, but if we want to have some more sane reasonings around memory and the memory model we shouldn't hesitate to bump our min-req to 1.5 + VK_KHR_vulkan_memory_model (Or Vulkan 1.2 which requires that ext). 

For all other APIs and versions of APIs we should have a really good discussion about the potential costs / merits about them; for example OpenGL support we probably should ignore entirely for now because it brings with it a whole new set of rules, guarantees (different memory model (!)) etc. Instead it's probably better for us right now to point people who don't want the Vulkan experience to something like wgpu that is more straight forward to use.

**Comment by repi** [comment]
Many different options here of what and how to specify it, though would be good to start with something decent.

So a few things off the top of my head.

Minimum SPIRV version: 1.3

Graphics API:
- Primary: native Vulkan 1.1
- Secondary: wgpu/gfx-rs can translate to Metal & DX12, but is extra layer and complexity
- Minimal effort, you are own your own: OpenGL

GPU:
- Primary: Nvidia and AMD Vulkan 1.1 / DX12 compatible GPU (most modern)
- Secondary: Recent Intel (can we specify a gen? does it matter?)

OS: 
- Primary: Windows 10 & Linux.   
    - Specify some recommended/used Linux variant (we use many)?
- Secondary: Mac Catalina+, supported to best of our ability. Goes through both API and shader translation (MoltenVK or gfx-portability) which adds complexity
- Later target: Android (modern) - will be a pain, but want to be able to test on it.

Drivers:
- Make sure you have latest available for your GPU and OS from the IHVs, (Nvidia, AMD, Intel) before filing issues
- Open source drivers may work, but you are on your own.

**Comment by khyperia** [comment]
> Minimum SPIRV version: 1.3

Just to be clear, we can't reach that right now, right? We need to fix wgpu to use vulkan 1.1 first.

**Comment by bjorn3** [comment]
> Open source drivers may work, but you are on your own.

On Linux the open source drivers are the official drivers for Intel and AMD and maintained by the respective vendor itself. The closed source driver from AMD is derived from the opensource and only exists for professional usage like CAD, not for gaming. Intel doesn't have a closed source driver. Only for Nvidia the opensource driver is not maintained by the vendor.
