### ISSUE TITLE
Emulate non-native instrs (e.g. uint128)

### ISSUE THREAD

**Issue by jon-chuang** [EmbarkStudios/rust-gpu#196]
One can possibly fully/partially emulate uint128 functionality by representing as two uint64s or whichever other capabilities are available. One can implement this generically so that any uint e.g. uint64 can be emulated with lower capabilities, e.g. uint32.

While this emulation can be done on the user side, it seems cleaner to expose emulated capabilities.

**Comment by jon-chuang** [comment]
One could possibly infer this at the instr emission stage from the operand ty. So at this point I’m not sure if the ty is rust types or `SpirvType`. I think it’s the latter.

**Comment by khyperia** [comment]
Just to get some background to help us place this on the roadmap, what are the use cases you have in mind for u128? Have you seen emulated u128s elsewhere before (e.g. GLSL)?

**Comment by jon-chuang** [comment]
Well the specific use-case I have is a 64 X 64 -> 128-bit wide mul and also add with carry used in cryptography.

**Comment by khyperia** [comment]
Yeah, we already keep track of what capabilities are available, so that part shouldn't be too difficult. It's just a hacked-together thing at this point, though, https://github.com/EmbarkStudios/rust-gpu/issues/42 tracks making it actually be useful. We probably want to wait until that system is more thought-out before tackling this.

**Comment by Jasper-Bekkers** [comment]
An additional note small note for feature orthogonality; it's unclear to me at this point how atomics would work on u128 and related types because of some of the remarks here: https://www.khronos.org/blog/comparing-the-vulkan-spir-v-memory-model-to-cs#_limited_forward_progress_guarantees (not saying it's impossible, just unclear to me).

**Comment by khyperia** [comment]
Yes, atomics would be disabled if using this feature set, I don't see any issues there. (Assuming there's no workaround, but, I'd say it's a pretty reasonable assumption)

**Comment by eddyb** [comment]
IIRC `rustc` used to have emulation for 128-bit integers on at least some targets, due to LLVM issues (sadly I don't remember more details). If someone wants to find that and retrofit it onto `rustc_codegen_spirv`, that might be an easy way to get support.

**Comment by DJMcNab** [comment]
It might be worth trying the [`extrprim`](https://lib.rs/crates/extprim) crate - the implementation for [`extprim::u128::u128`](https://docs.rs/extprim/1.7.1/extprim/u128/struct.u128.html) at first glance doesn't look like it uses anything we wouldn't support, and it is normally `no_std`

**Comment by XAMPPRocky** [comment]
We discussed at the meeting today, and the consensus was that emulating wider integers such u128 isn't a priority for us, however we would accept a contribution from the community for it. Provided, that the code contributed is relatively straightforward and maintainable.

**Comment by khyperia** [comment]
I don't think this is on the roadmap for us, and I'm not sure we would accept a community solution due to the maintenance burden, so closing this for now.

**Comment by LegNeato** [comment]
https://github.com/rust-lang/rust/issues/116909
