### ISSUE TITLE
Render graph design

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/rust-gpu#21]
A high-level goal for this project is to also design a GPU rendering/compute graph to tie it all together and enable users to to develop small reusable graph components inside crates that contain Rust CPU and GPU code and that can be easily connected and tweaked.

We talked briefly about it today in #15, but will require quite a bit of design and the lower level parts of SPIRV codegeneration and Rust bindings overall (#10) is higher priority

**Comment by repi** [comment]
As we said in the meeting yesterday (#227) feel free to discuss goals, high-level designs, and gather references from other implementations for this here in the issue. cc @vojd 

If it does start getting somewhat extensive, could also just write it up an a markdown file and check in. I think later for the design phase we'll go through MCE / RFCs but also prototypes directly in our engine codebase (Ark)

**Comment by TrueDoctor** [comment]
For [Graphite](https://github.com/GraphiteEditor/Graphite) we are developing a node based image editor where every node is a rust function that can be executed on the cpu/gpu. The user can then modify the nodegraph visually which is then either dynamically linked or ad hoc compiled and executed. We probably target an even more high level/abstract user experience then you would try to provide, but the issues that come up during our implementation could potentially inform your design.
+ Embark could potentially profit from a software such as graphite because it would be trivial to integrate your own tools as nodes in a graph and use the already provided ui. The project is of course fully open source.

**Comment by repi** [comment]
closing this old issue because we already have a GPU render graph in `kajiya` as well as our own production renderer.

@TrueDoctor I think the type of render node graph you are talking about is a different thing, this was specifically about coordinating GPU rasterization/raytracing/compute passes on the GPU and it is memory management. for early work on it see the [FrameGraph in Frostbite](https://www.gdcvault.com/play/1024612/FrameGraph-Extensible-Rendering-Architecture-in)
