### ISSUE TITLE
Investigate inferring storage class

### ISSUE THREAD

**Issue by khyperia** [EmbarkStudios/rust-gpu#300]
Instead of having explicit pointer-wrapping types in `spirv-std` like `Input<T>`, instead, have the compiler not emit storage classes at all (using `Generic` as a placeholder or something, even though that's not what `Generic` storage class means). Then, in the linker, do a whole-program-analysis and propagate storage classes throughout the program. Essentially, treat any place where a pointer type appears as a "generic type parameter" except it's a "generic storage class parameter", then do monomorphization (so duplicating functions that are called with multiple storage classes, etc.).

This would solve many problems:

- Constants could be emitted to OpVariables of Private storage class, and pointers to them could be passed to functions.
- OpTypeRuntimeArray would be able to be supported really easily, as the current `Input<T>` system requires loading a value of `T`, but with OpTypeRuntimeArray, `T` is unsized. Rust's normal rules around this work great, if it were `&T`, you could write `obj.the_unsized_array[5]` and it'd generate the right code with the right storage classes.
- This looks really really nice:
  ```rust
  fn main (#[spirv(input)] input: &f32, #[spirv(output)] output: &mut f32) {}
  ```

**Comment by charles-r-earp** [comment]
Function is the default right now, so just removing the storage class attributes on structs would be enough. I don't think there needs to be a placeholder, just leave them as Function and then in a linker pass it should be possible to propagate the correct storage class. Otherwise all the code that asserts that types (and storage classes) are equal would have to be changed to allow for Generic == Other. 

I would suggest handling block decorations this way as well.

Firstly, is it even possible to have a slice as an argument to a pub fn in a dylib? I thought that Rust doesn't have a stable abi for slices and so this causes issues.

So, do you want to just declare the entry variable with the storage class (but not the pointer?), assuming this doesn't cause issues? This would tag the variable for later, will the pointer storage class would be Function and operate normally. 

This was more or less what I was trying to do in #235. While doable, it would probably need to gather a graph of all the deps of a variable, rather than just a few hashmaps because searching is recursive and deep. This interacts with a whole host of operations, not just access chains and loads / stores, but OpPhi as well. Ideally this would occur earlier than I did it and before a lot of optimizations and instructions, but that requires more reflection. 

Not only does this look nice, it also makes it easier to use "non-gpu" code, with the only real constraint being no_std. Otherwise that code would have to be generic over the storage class, or written specifically for a particular storage class, or purely copy in copy out, can't interact with slices.

**Comment by eddyb** [comment]
> Firstly, is it even possible to have a slice as an argument to a pub fn in a dylib? I thought that Rust doesn't have a stable abi for slices and so this causes issues.

`staticlib`/`cdylib` don't really have ABI interactions, there's only some warnings for using Rust types in `extern "C"` functions but none of that should matter when compiling for SPIR-V.

**Comment by eddyb** [comment]
I think in order to be able to handle pointers nested in aggregates, I would take this approach:
* all the types are lowered as `Generic` (in lieu of a better replacement)
* constant data is represented as `Private` module-scoped `OpVariable`s
* local variables are represented as `Function` (like today) `OpVariable`s
* any specially marked pointers get whichever storage class is necessary

This will produce invalid SPIR-V due to the type mismatches. So the inference pass effectively becomes a "subtyping specialization" or "type reconciliation"  pass, which keeps collecting all possible function signatures per function.

This still won't support `if condition { &GLOBAL } else { &local }` though, for that we'll need emulation.
But at least we could detect that as a sort of "type mismatch". Ideally we'd be emitting enough `OpLine`s to report it as an user error, otherwise the experience could get pretty bad.
