### ISSUE TITLE
"Build system"

### ISSUE THREAD

**Issue by khyperia** [EmbarkStudios/rust-gpu#48]
This is a tracking issue for what I've been calling the "build system", but in reality the full task list is larger than just that.

In general, this is a group of related issues that would be great for someone other than me to own and drive forwards. These tasks are spread across various "functionality levels", see that issue for more information.

- Create a crate to be used by users build.rs, that takes a path to a shader crate and spits back a spir-v binary that can be `include!`d (or perhaps a better designed version of this). I've created an extremely rough and minimally-featured prototype in the [spirv-builder](https://github.com/EmbarkStudios/rust-gpu/tree/main/spirv-builder) crate - we need to expand it quite a bit, in both robustness and features.
- Integrate spirv-opt and spirv-val into statically linkable libraries that are included in rustc_codegen_spirv. This means the user will not have to install spirv-tools on their system. Tracking issue: https://github.com/EmbarkStudios/rust-gpu/issues/31
- Generate host-side bindings, tracking issue: https://github.com/EmbarkStudios/rust-gpu/issues/10. I like the approach of "SYCL compiles down it's GPU side C++ code along with some side-cart metadata first, this metadata is then converted into regular host side C++". This means that rustc_codegen_spirv would spit out some form of metadata for what bindings are in the module, and then the build.rs helper crate would generate rust source files from that metadata. (Or perhaps rustc_codegen_spirv would spit out rust files directly and the builder would just include them, but, whatever, exact behavior to be determined later. Having multiple backends - e.g. ash and vulkano both - complicates this.)
- Possibly adding any hooks/etc. to that generated code to enable the rendergraph/flamegraph support.

**Comment by XAMPPRocky** [comment]
I've been thinking about this quite a bit in past couple of days, in relation to testing the crate, as right now we use `spirv-builder` for the tests and it complicates the testing process for a lot of the same reasons it's complicated for users. I think there's a few modifications to how we're building that would dramatically simplify the process. First I want to outline who we are targeting with the build system.

- **Users** People or organisations who want to use rust-gpu in their projects but don't want to contribute or modify themselves. Builds should be easy for them to setup and use in their projects.
- **Contributors** People or organisations who want to use and contribute to rust-gpu, they want to be able to build and test their changes. Builds should as close to CI as possible.
- **CI** Continuous Integration wants to be able to easily build and test entirely from scratch. Builds should be fast and easy to re-produce for debugging.

---

I think the following changes together would drastically simplify the build process, and make `rust-gpu` both easier to test and use.

1. Dropping `cargo` for building sysroot in favour of building it with `rustc` directly.
2. Adding the option to use an install the `spirv-unknown-unknown` sysroot and `rustc_codegen_spirv` shared library to your system.
3. Moving `spirv-builder` building `rustc_codegen_spirv` to be at runtime.
4. Changing `spirv-builder` into our `rust-gpu` build and testing library/tool both for development and users. (Similar to `x.py` from rust)
  - Adding a CLI with the following commands
    - `test` command which runs the entire testsuite. This would replace the current shell scripts, and unify testing between CI and local development. It would also allow adding additional testing steps with non rust/cargo tools, such as using `mdbook-linkcheck` for checking that hyperlinks in the dev guide are all working.
    - `build` like test but only builds.
    - `install` command to build and install a release version of `rust-gpu` to your system.

 I've laid out the motivation for each of the changes below. 

1. Right now the dependency on using cargo to build sysroot complicates testing and using `spire-builder`. Tests need to build serially to re-use libcore, and any user of `spirv-builder` needs to also be using cargo for their build system. Ideally the crate should be able to build without invoking cargo at all, and we should allow user's to integrate with their existing build systems.
2. In tandem with 1 and managing our own sysroot, we could install it and the final shared library somewhere where they could be re-used. This would be great for users as they could just use `-Z codegen-backend` and have it work, and for tests since we could built and install ahead on CI and run the integrations tests on a prebuilt backend. We could even go slightly further for users and provide shell aliases (e.g. `rustc-gpu=$(rustc +nightly-YYYY-MM-DD -Z codegen-backend=./path)`. )
	- We need to ensure we're running on the same nightly the installed version was compiled with it. But `rustc_codegen_spirv` could be able to handle checking that by embedding the compiled version hash and invoking `rustc` on entry for its version.
	- We'd still retain an option to build and run entirely within the build script like today.
3. Currently we're compiling `rustc_codegen_spirv` with `spirv-builder` as it makes it the implementation simpler by exposing `rustc_codegen_spirv` through `LD_LIBRARY_PATH`. But this has also had a side-effect where the `use-installed-tools` and `use-compiled-tools` features have to be propagated into crates in order to provide that option. This makes it quite annoying to add new crates (such as examples or tests) in the repository, as they really shouldn't have to expose features to be tested with either of those tools.
	- Moving this dependency to runtime would it make easier to test both without propagating feature flags, and would allow us to add some ergonomics where we could detect if tools are installed first before compiling them.
4. In relation to all of the above it's already becoming hard to "fully" test the project locally, as right now there isn't a single command that will perform the tests. Having this functionality in a single tool (and probably a single command) makes it a lot easier to test and be confident that your code is ready for review.

At the end of the day this is the expected flow for each of the use cases with the proposed changes.

**User**
Install workflow:
- `git clone <EmbarkStudios/rust-gpu>`
- `cargo run -p spirv-builder install`
- (In the future those first two steps could be shipped as a `cargo-install` script, so something like `cargo install rust-gpu` invokes a build script that does those steps for you.)
- Done, you should be able to use `-Z codegen-backend` with nightly rust directly.

In build scripts:
```rust
// In build.rs
fn main () {
   // Pseudo code (This could also be a single function that takes an enum.)
   SpirvBuilder::auto_detect(build_dir)?;
   SpirvBuilder::use_installed(build_dir)?;
   SpirvBuilder::from_source(build_dir)?;
	// For people who just want locations and don't want us to set flags.
   let (sysroot, codegen_backend_path) = builder.get_sources(build_dir)?;
}
```

**Contributor**
- `git clone <EmbarkStudios/rust-gpu>`
- `cargo run -p spirv-builder install` (optional)
- Makes changes
- `cargo run -p spirv-builder test` (default will auto-detect if you have tools installed and use those for building)

**CI**
- `git clone <EmbarkStudios/rust-gpu>`
- `cargo run -p spirv-builder install`
- `cargo run -p spirv-builder test --use-installed-tools`
- `cargo run -p spirv-builder test --use-compiled-tools`

**Comment by bjorn3** [comment]
> Adding the option to use an install the spirv-unknown-unknown sysroot and rustc_codegen_spirv shared library to your system.

You can add it as `$(rustc --print sysroot)/lib/rustlib/$HOST_TRIPLE/lib/codegen-backends/librustc_codegen_spirv-$RUST_RELEASE.so`. I think it would make sense to change the required dir to `$(rustc --print sysroot)/lib/codegen-backend` or `$(rustc --print sysroot)/lib/rustlib/codegen-backend` though.

**Comment by khyperia** [comment]
> Then it will be available as `rustc -Zcodegen-backend=spirv`.

Wait what?!? I haven't seen or found code for that anywhere in rustc, could you point it out? I've only seen the codepaths for "here's a filename, dlopen it" and then a hardcoded "if it's the string llvm, or now cranelift, load the statically linked backend".

**Comment by bjorn3** [comment]
It turns out that it is also possible to add it to a sysroot passed using `--sysroot`, not just the one part of rustc itself: https://github.com/rust-lang/rust/blob/8e8939b8045b7af6076fb718e2e298844aaf4650/compiler/rustc_interface/src/util.rs#L409

> Wait what?!? I haven't seen or found code for that anywhere in rustc, could you point it out? I've only seen the codepaths for "here's a filename, dlopen it" and then a hardcoded "if it's the string llvm, or now cranelift, load the statically linked backend".

That is [`get_codegen_sysroot`](https://github.com/rust-lang/rust/blob/8e8939b8045b7af6076fb718e2e298844aaf4650/compiler/rustc_interface/src/util.rs#L396) which I re-introduced in https://github.com/rust-lang/rust/pull/77975 to load cg_clif when built as part of rustc.

**Comment by khyperia** [comment]
oh! haha, apparently haven't `git pull`'d on rust-lang/rust in a while, so that's why my `rg codegen-backends` didn't show up with anything :P

**Comment by joonazan** [comment]
I have two issues with spirv-builder.

1. The version on crates.io is useless.
2. Unless I use the lockfile in this repo, I get the error shown below.
```
  --> /home/joonazan/rust-gpu/crates/rustc_codegen_spirv/src/lib.rs:57:1
   |
57 | extern crate rustc_ast;
   | ^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

```

**Comment by XAMPPRocky** [comment]
> The version on crates.io is useless.

This is intentional currently, we're not publishing releases to crates.io at the moment.

**Comment by XAMPPRocky** [comment]
A recent development that could change this, is the new "artifact dependencies" Cargo RFC (https://github.com/rust-lang/rfcs/pull/3028), which will allow you to specify an artifact dependency in cargo (See example below). I think if this RFC is accepted and implemented, it will negate most if not all of the need for `spirv-builder` and #239. Though of course this RFC is still being discussed and I'm not sure what our urgency is to have a better build system in the near term.

```toml
sky-shader = { path = "./sky-shader", artifact = "cdylib", target = "spirv-unknown-unknown" }
```

```rust
const SHADER: &[u8] = include_bytes!(env!("CARGO_CDYLIB_DIR_SKY_SHADER"));
```

**Comment by khyperia** [comment]
We've figured out the build system enough, and things work well enough, that we should probably make more focused issues on particular problems we're having, or feature desires (e.g. the cargo artifact dependency RFC)
