### ISSUE TITLE
Dead types not stripped

### ISSUE THREAD

**Issue by hrydgard** [EmbarkStudios/rust-gpu#531]
In SPIR-V output, one can find various types that should not remain after optimization and dead code elimination, that are actually invalid and will trip up some drivers. 

This can be things like:
```
%_ptr_Function__ptr_Input_v3float = OpTypePointer Function %_ptr_Input_v3float
```
but I think there are other variations too.

These violate the following restriction:

```
A variable pointer must point to one of the following storage classes:
* StorageBuffer
* Workgroup (if the VariablePointers capability is declared
```

Unfortunately these do seem to pass spir-val, so that's a separate problem.

**Comment by expenses** [comment]
try running `spirv-opt <file> -O -o <file>`. It's pretty good for dead code removal, that's what I use it for at-least.

**Comment by khyperia** [comment]
The reason this happens is a little awkward - the linker runs DCE (which includes dead types) after most linker steps, but _before_ structurization and mem2reg. This means that if mem2reg (which is done for legalization purposes, to remove references to these very types) removes references to a type, it won't get removed. I'll PR a fix adding a second DCE pass after mem2reg (can't move the first DCE to after mem2reg AFAIK, because it's placed there for perf reasons, since structurization is slow)
