### ISSUE TITLE
Use target features for capabilities

### ISSUE THREAD

**Issue by XAMPPRocky** [EmbarkStudios/rust-gpu#555]
# Proposal
While working on #529 I was thinking about other approaches we could take, and one that I would like to propose we do instead adding a new attribute is to use `-Ctarget-features` for describing what capabilities to use. As I've thought over I think this has a few important advantages over the current proposed approach.

- More "Rust-tic" — Since target-features is built-in to the compiler, more people are familiar with using `target-feature` for controlling CPU capabilities so using it for GPU capabilities is more intuitive than a custom attribute. This also helps with development as we can use any ecosystem features or integrations that use `target-feature`.
- Cfgable — Using target-feature gives us a free cfg predicate to use in our GPU code. For example you'd be able to write `#[cfg(target_feature = "MultiView")]` to write code that only works when `MultiView` is available.
- Binary focused — Target features can really only be set when you're building the final binary, so a library can't currently enable it for you behind the scenes. This matches the behaviour we wanted to have where you only set the capabilities you need when compiling the final shader.

**Comment by khyperia** [comment]
Discussed in yesterday's meeting, we'd like to go with this solution rather than attributes~

**Comment by khyperia** [comment]
Precise design for both capabilities and extensions:

- Capabilities will not have a prefix, and will be specified via `+MultiView` (capitalized as the original spir-v spec spelling, not snek case), and `#[cfg(target_feature = "MultiView")]`. This is okay because the set of extensions is known ahead of time and can be checked for good names, and pascal case because auto-snek-casing things with names like `SubgroupBallotKHR` is annoying/weird (rspirv already has FromStr for capability for pascal case), and also lets people look up the spir-v spec and copypaste the exact name in without trying to guess how it's snek cased.
- Extensions will have an `ext:` prefix, then an arbitrary string - `+ext:SPV_KHR_vulkan_memory_model`, `#[cfg(target_feature = "ext:SPV_KHR_vulkan_memory_model")]`. Quotes are _not_ included. Validity of it being a known extension is _not_ checked.
