### ISSUE TITLE
Branchy code is produced for `f32.powi` even though it should be handled by an intrinsic

### ISSUE THREAD

**Issue by expenses** [EmbarkStudios/rust-gpu#795]
Here we convert the `sym::powif32` intrinsic into the `Pow` glsl extension instruction.
https://github.com/EmbarkStudios/rust-gpu/blob/28313a2029aec5de7283e167ea2d67d2aa350f62/crates/rustc_codegen_spirv/src/builder/intrinsics.rs#L152-L155

However, in practise this conversion doesn't seem to happen. This compiletest:

```rust
// build-pass
// compile-flags: -C llvm-args=--disassemble-fn=powi::main

use spirv_std::num_traits::Float;

#[spirv(fragment)]
pub fn main() {
    let exponentiation = 5.0_f32.powi(5.0);
    assert!(exponentiation == 3125.0);
}
```

Produces [this SPIR-V](https://gist.github.com/expenses/0aec3fd2dc03166b85d4ef2b1cf691d1) (too long to be inserted here). I presume this isn't working as intended, right?

**Comment by khyperia** [comment]
To explain what's going on here, `f32::powf` is only implemented in std, not in core. So, it's is calling `num-traits`'s `powf`, which calls `libm::powf` https://docs.rs/num-traits/0.2.14/src/num_traits/float.rs.html#2010 which should get intercepted here https://github.com/EmbarkStudios/rust-gpu/blob/04146858ce1fc631717db21071b99b8101e12cda/crates/rustc_codegen_spirv/src/builder/libm_intrinsics.rs#L156 rather than the place you linked (note you linked to the wrong thing in intrinsics.rs, too, probably should link to powf32, not powif32, if you're calling powf in rust instead of powi). The intrinsics.rs implementation is theoretically dead code (but might not be in the future if upstream rust changes, so, keeping it).

Not sure why _that_ code path doesn't work, maybe something is outdated (we've had issues with old versions of num-traits in the past), or I'm not understanding num-traits fully.

**Comment by expenses** [comment]
Oops, sorry. The compiletest I embedded above was wrong. The problem is not with `f32.powf` (which works fine) but with `f32.powi`.

**Comment by expenses** [comment]
But your link does explain what's going on. It's calling this code for `powi`: 

https://docs.rs/num-traits/0.2.14/src/num_traits/float.rs.html#675-685

I'm confused why they don't use an intrinsic internally though.

**Comment by hrydgard** [comment]
powi is very rarely used outside powi(2) and powi(3), maybe some "early" specialization can be made ..

**Comment by expenses** [comment]
> powi is very rarely used outside powi(2) and powi(3), maybe some "early" specialization can be made ..

I stumbled apon this while implementing fresnel_schlick which does powi(5) :P

**Comment by hrydgard** [comment]
Hah, well, I'd call that the exception that proves the rule :P

**Comment by khyperia** [comment]
I think this is a fully external issue, then - rust-gpu is working "as intended", faithfully compiling the code that it is given, which doesn't use an intrinsic. The way to fix this, then, would be to change upstream code to be less branchy (e.g. requesting that libm adds a powi intrinsic, and having num-traits call it).

**Comment by hrydgard** [comment]
That is fair enough, and probably the way to go indeed.
