### ISSUE TITLE
Some kind of clippy-esque warning system for rust core functions that are known to be branchy.

### ISSUE THREAD

**Issue by expenses** [EmbarkStudios/rust-gpu#796]
`f32.clamp`, `f32.lerp` and the [int min/max functions](https://github.com/EmbarkStudios/rust-gpu/issues/758) are all known to be quite branchy. It'd be fantastic if there was some system to detect their use and to recommend alternatives.

**Comment by expenses** [comment]
This seems like it's something that the clippy [`disallowed_method`](https://rust-lang.github.io/rust-clippy/master/index.html#disallowed_method) lint should be able to do, but I haven't gotten that to work thus far.

**Comment by hrydgard** [comment]
I made this point in another issue, but in some cases, it might even make sense to contribute simplifications upstream to Rust, because for some of these there's little reason other than implementation "elegance" that their implementations are so crazy complex / optimizer-reliant as they are. Might even speed up Rust CPU compiles noticeable.

**Comment by khyperia** [comment]
The best clippy-esque system is clippy itself, IMO, so I've [filed an issue](https://github.com/rust-lang/rust-clippy/issues/8079) to get support for this. Closing this to track it on clippy instead.

**Comment by repi** [comment]
the clippy lint support is implemented now, so probably comes out in nightly soon and one can test with this. So maybe we should re-open this to test using it for the lerp functions on the example shaders in the repo?
