### ISSUE TITLE
repr(simd) for matrix types

### ISSUE THREAD

**Issue by Jasper-Bekkers** [EmbarkStudios/rust-gpu#82]
This is super low prio because I don't think anybody actually cares about OpTypeMatrix at the moment, but it might be nice to have.

**Comment by termhn** [comment]
related to this and also kinda #121 , what does repr(simd) actually do on these gpu types?

**Comment by khyperia** [comment]
Inside rustc, `repr(simd)` types are called ["Vector"](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_target/abi/enum.Abi.html#variant.Vector), and, we just translate those directly to spir-v [OpTypeVector](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpTypeVector).

https://github.com/EmbarkStudios/rust-gpu/blob/8681464af7e2500f371e5df6a95691cf29ecd16a/rustc_codegen_spirv/src/abi.rs#L336-L343

So, this issue isn't actually about `repr(simd)` for matrix types, because we can't hijack the existing system for that, but rather probably creating a spirv builtin attribute that translates the struct to be OpTypeMatrix, but whatever, close enough. (The attribute would not publicly documented and only used in spirv-std, similar to the current `storage_class`)

**Comment by Boscop** [comment]
> This is super low prio because I don't think anybody actually cares about `OpTypeMatrix` at the moment, but it might be nice to have.

I care about it :) 
In fact for my use case I need `Mat3` and `Mat4` as uniforms that match the native `mat3`/`mat4` types.

**Comment by khyperia** [comment]
I don't think this is on our roadmap any time soon, but is a relatively self-contained nugget of a task that a community member could feasibly do that wouldn't interfere much with anything else, so I'll leave this open for now even though it's technically kind of a `wontfix`.
