### ISSUE TITLE
Android CI is failing

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/rust-gpu#890]
Our CI is failing on Android with:

```
Build WGPU example for Android
  Warning: You use environment variable ANDROID_HOME that is deprecated. Please, remove it and use ANDROID_SDK_ROOT instead. Now ANDROID_HOME is used
  Error: Android NDK is not found. Please set the path to the Android NDK with $ANDROID_NDK_ROOT environment variable.
  Error: Process completed with exit code 1.
```

Example: https://github.com/EmbarkStudios/rust-gpu/runs/7635577970?check_suite_focus=true

May be related to the following GitHub Action ubuntu image updates:
- https://github.com/actions/virtual-environments/issues/5930
- https://github.com/actions/virtual-environments/issues/5879

**Comment by repi** [comment]
This is how we fixed it in the physx repo just now: https://github.com/EmbarkStudios/physx-rs/pull/155

@eddyb can you try similar here, or @oisyn next week when back from vacation

**Comment by MarijnS95** [comment]
This is https://github.com/actions/virtual-environments/issues/5879#issuecomment-1195156618, `ndk-bundle` was deprecated and removed but these useful symlinks were removed by "accident" as well. Should be fixed soon!

**Comment by eddyb** [comment]
> This is how we fixed it in the physx repo just now: https://github.com/EmbarkStudios/physx-rs/pull/155

That repo's CI seems to have been setting `ANDROID_NDK_ROOT` before, but here we didn't.

Hoping that the GHA fixes @MarijnS95 linked have already been propagated, I [forced a re-run](https://github.com/EmbarkStudios/rust-gpu/runs/7702335111) of the failing CI job, but before it can even get to the part where it uses the NDK, it now fails building `cargo-apk` [because `libc 0.2.127` is broken for the nightly we use](https://github.com/rust-lang/libc/commit/576f77814cff61d0ed7e30f2a7d0f0f696001bd5#commitcomment-80215910).

Even if we unblock `cargo-apk` specifically, we'll have to be careful to avoid bumping `libc`: https://github.com/EmbarkStudios/rust-gpu/blob/0866cf591a7fdbbd15bdb3468e192bb9b6189fd0/Cargo.lock#L1183-L1185

(until we rustup again, that is)

I'll try see what I can do for now, maybe `cargo +stable install ...` will be enough.
